version: "3.7"

services:
  test_postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "test_postgres"
      POSTGRES_PASSWORD: "test_postgres"
      POSTGRES_DB: "test_postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_mysql:
    image: "mysql"
    environment:
      MYSQL_USER: "test_mysql"
      MYSQL_PASSWORD: "test_mysql"
      MYSQL_DATABASE: "test_mysql"
      MYSQL_ROOT_PASSWORD: 'test_mysql'
    volumes:
      - mysql_data:/var/lib/mysql/data

  test_mariadb:
    image: "mariadb"
    environment:
      MYSQL_USER: "test_mariadb"
      MYSQL_PASSWORD: "test_mariadb"
      MYSQL_DATABASE: "test_mariadb"
      MYSQL_ROOT_PASSWORD: 'test_mariadb'
    volumes:
      - mariadb_data:/var/lib/mariadb/data

  test_sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite_data/:/root/db/
      
  test_mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: '0:0'
    ports:
      - 1433:1433
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass@word"
      MSSQL_PID: "Express"
      
volumes:
  postgres_data:
  mysql_data:
  mariadb_data:
  sqlite_data:
